# Generated by Django 4.1.1 on 2022-10-04 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cie10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7)),
                ('diagnostico', models.CharField(max_length=50)),
                ('grd', models.CharField(max_length=10)),
                ('sev', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Cie10',
                'verbose_name_plural': 'Cie10s',
                'db_table': 'cie10',
            },
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ir_grd', models.CharField(max_length=10)),
                ('nombregrd', models.CharField(max_length=50)),
                ('numaltash', models.SmallIntegerField()),
                ('sumaestancia', models.IntegerField()),
                ('eminlier', models.FloatField()),
                ('pcsuperior', models.SmallIntegerField()),
                ('pesogrd', models.FloatField()),
                ('preciofonasa', models.FloatField()),
            ],
            options={
                'verbose_name': 'Norma',
                'verbose_name_plural': 'Normas',
                'db_table': 'norma',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permiso',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicio',
            },
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionPacientes.roles'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rut',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='roles',
            table='rol',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuario',
        ),
        migrations.AddField(
            model_name='roles',
            name='permisos',
            field=models.ManyToManyField(to='gestionPacientes.permisos'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionPacientes.servicio'),
        ),
    ]
