# Generated by Django 4.1.1 on 2022-10-05 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0002_cie10_norma_permisos_servicio_alter_roles_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidoPaterno', models.CharField(max_length=30)),
                ('apellidoMaterno', models.CharField(max_length=30)),
                ('sexo', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('fechaCarga', models.DateField()),
                ('ultimaCama', models.IntegerField()),
                ('diasEstancia', models.IntegerField()),
                ('previsionDesc', models.CharField(max_length=30)),
                ('codigoPlanSalud', models.CharField(max_length=10)),
                ('planSaludDesc', models.CharField(max_length=10)),
                ('fechaIngreso', models.DateField()),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionPacientes.servicio')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cama', models.IntegerField()),
                ('nombrePaciente', models.CharField(max_length=30)),
                ('estancia', models.IntegerField()),
                ('diagnostico1', models.CharField(max_length=30)),
                ('diagnostico2', models.CharField(max_length=30)),
                ('emNorma', models.IntegerField()),
                ('pcSuperior', models.IntegerField()),
                ('pesoGRD', models.FloatField()),
                ('pago', models.FloatField()),
                ('ir_grd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionPacientes.servicio')),
                ('rut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionPacientes.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('condP', models.FloatField()),
                ('emaf', models.FloatField()),
                ('iema', models.FloatField()),
                ('peso', models.FloatField()),
                ('emafInliers', models.FloatField()),
                ('iemaInliers', models.FloatField()),
                ('outliers', models.FloatField()),
                ('pInt', models.FloatField()),
                ('pExt', models.FloatField()),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionPacientes.servicio')),
            ],
            options={
                'verbose_name': 'ReporteMensual',
                'verbose_name_plural': 'ReportesMensuales',
                'db_table': 'reporteMensual',
            },
        ),
        migrations.CreateModel(
            name='Pendientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePendiente', models.CharField(max_length=30)),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionPacientes.servicio')),
            ],
            options={
                'verbose_name': 'Pendiente',
                'verbose_name_plural': 'Pendientes',
                'db_table': 'pendiente',
            },
        ),
    ]
