# Generated by Django 4.1.1 on 2022-10-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0003_pacientes_resumen_reportemensual_pendientes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumen',
            options={'verbose_name': 'Resumen', 'verbose_name_plural': 'Resumenes'},
        ),
        migrations.AlterModelTable(
            name='resumen',
            table='resumen',
        ),
    ]
