# Generated by Django 4.1.1 on 2022-10-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0005_relationship_profile_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
