# Generated by Django 4.1.1 on 2022-10-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0007_remove_profile_user_remove_relationship_from_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='norma',
            old_name='eminlier',
            new_name='emInlier',
        ),
        migrations.RemoveField(
            model_name='norma',
            name='numaltash',
        ),
        migrations.RemoveField(
            model_name='norma',
            name='preciofonasa',
        ),
        migrations.RemoveField(
            model_name='norma',
            name='sumaestancia',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='codigoPlanSalud',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='planSaludDesc',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='previsionDesc',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='pendientes',
            name='servicio',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='diagnosticos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendientes',
            name='causa',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
