# Generated by Django 4.1.1 on 2022-10-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0008_rename_eminlier_norma_eminlier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cie10',
            name='diagnostico',
            field=models.CharField(max_length=100),
        ),
    ]
