# Generated by Django 4.1.1 on 2022-10-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0009_alter_cie10_diagnostico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cie10',
            name='diagnostico',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='diagnosticos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='diagnostico1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='diagnostico2',
            field=models.CharField(max_length=200),
        ),
    ]
