# Generated by Django 4.1.1 on 2022-10-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0010_alter_cie10_diagnostico_alter_pacientes_diagnosticos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cie10',
            name='diagnostico',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='diagnosticos',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='diagnostico1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='diagnostico2',
            field=models.CharField(max_length=250),
        ),
    ]
