# Generated by Django 4.1.1 on 2022-10-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0011_alter_cie10_diagnostico_alter_pacientes_diagnosticos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='norma',
            old_name='pcsuperior',
            new_name='pcSuperior',
        ),
        migrations.RenameField(
            model_name='norma',
            old_name='pesogrd',
            new_name='pesoGRD',
        ),
        migrations.RemoveField(
            model_name='norma',
            name='nombregrd',
        ),
        migrations.AddField(
            model_name='norma',
            name='nombreGRD',
            field=models.CharField(default='-', max_length=150),
            preserve_default=False,
        ),
    ]
