# Generated by Django 4.1.1 on 2022-10-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0012_rename_pcsuperior_norma_pcsuperior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen',
            name='cama',
            field=models.IntegerField(null=True),
        ),
    ]
