# Generated by Django 4.1.1 on 2022-10-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0015_alter_resumen_nombrepaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen',
            name='cama',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
