# Generated by Django 4.1.1 on 2022-10-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0016_alter_resumen_cama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen',
            name='estancia',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
