# Generated by Django 4.1.1 on 2022-10-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0017_alter_resumen_estancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen',
            name='ir_grd',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
