# Generated by Django 4.1.1 on 2022-10-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0019_remove_resumen_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='apellidoMaterno',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='apellidoPaterno',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='nombre',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='diagnostico2',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
